name: sml_professional
description: Enterprise-grade mobile application for Spoorthi MACS Ltd. (SML) - Professional loan management and field operations app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core Flutter packages
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.1.1
  get: ^4.6.6
  
  # Networking & API
  http: ^1.1.0
  dio: ^5.3.2
  connectivity_plus: ^5.0.2
  
  # Authentication & Security
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  # photo_view: ^0.14.0  # Temporarily disabled
  google_fonts: ^6.1.0
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # File Handling
  file_picker: ^6.1.1
  path: ^1.8.3
  
  # QR Code & Barcode
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Excel Export
  # excel: ^2.1.0  # Temporarily disabled
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Offline Support
  sqflite: ^2.3.0
  
  # Real-time Updates
  # web_socket_channel: ^2.4.0  # Temporarily disabled
  
  # Internationalization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
