app = "sml777-app"
primary_region = "dfw"

[build]

[env]
  DJANGO_SETTINGS_MODULE = "spoorthi_macs.settings"
  DEBUG = "False"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

