services:
  - type: web
    name: sml777-app
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
      python manage.py shell -c "
      from django.contrib.auth import get_user_model
      User = get_user_model()
      if not User.objects.filter(username='admin').exists():
          User.objects.create_superuser('admin', 'admin@example.com', 'admin123')
          print('Superuser created: admin/admin123')
      else:
          print('Superuser already exists')
      "
    startCommand: gunicorn spoorthi_macs.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: spoorthi_macs.settings_minimal
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sml777-db
          property: connectionString
      - key: ADMIN_EMAIL
        value: admin@yourdomain.com
      - key: SML_BUREAU_PROVIDER
        value: CIBIL
      - key: RAZORPAY_PROVIDER
        value: RAZORPAY
      - key: CUSTOM_DOMAIN
        value: ""
    autoDeploy: true

databases:
  - name: sml777-db
    plan: free
    region: oregon