# Generated by Django 5.2.5 on 2025-08-19 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('raw_csv_data', models.JSONField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('account_no', models.CharField(blank=True, max_length=30)),
                ('member_code', models.CharField(blank=True, max_length=30)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GatewayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=32)),
                ('event', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('signature_ok', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'companies_gatewayevent',
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('raw_csv_data', models.JSONField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('member_code', models.CharField(blank=True, max_length=30)),
                ('mortgage_date', models.DateField(blank=True, null=True)),
                ('property_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('deed_no', models.CharField(blank=True, max_length=64, null=True)),
                ('mortgage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collateral_val', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=8)),
                ('to_address', models.CharField(max_length=128)),
                ('subject', models.CharField(blank=True, max_length=120, null=True)),
                ('body', models.TextField()),
                ('status', models.CharField(default='queued', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'companies_notification',
            },
        ),
        migrations.CreateModel(
            name='Prepaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('raw_csv_data', models.JSONField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('member_code', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='StaffCode', limit_choices_to=models.Q(('status__iexact', 'active'), ('status', '1'), ('status', 1), ('status', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='companies.staff', to_field='staffcode'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=8)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companies_auditlog',
            },
        ),
        migrations.CreateModel(
            name='LoanRestructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('raw_csv_data', models.JSONField(blank=True, null=True)),
                ('old_tenure', models.PositiveIntegerField()),
                ('old_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_tenure', models.PositiveIntegerField()),
                ('new_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restructures', to='companies.loanapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('raw_csv_data', models.JSONField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('gateway', models.CharField(default='stub', max_length=32)),
                ('status', models.CharField(default='created', max_length=16)),
                ('txn_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='companies.loanapplication')),
            ],
            options={
                'db_table': 'companies_payment',
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('raw_csv_data', models.JSONField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode', models.CharField(blank=True, max_length=32, null=True)),
                ('reference', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='companies.loanapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EWIFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('detail', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ewi_flags', to='companies.loanapplication')),
            ],
            options={
                'db_table': 'companies_ewiflag',
                'indexes': [models.Index(fields=['loan_application', 'active', 'code'], name='companies_e_loan_ap_334ccc_idx')],
            },
        ),
    ]
