# Generated by Django 5.2.5 on 2025-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_aadhar_accfundloancols_accfundloans_accheads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(blank=True, help_text='Username for the Django user account', max_length=150, null=True, verbose_name='User'),
        ),
    ]
