# Generated by Django 5.2.5 on 2025-08-19 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_exsaving_gatewayevent_mortgage_notification_prepaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldschedule',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='StaffCode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.staff', to_field='staffcode'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='StaffCode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile_set', to='companies.staff', to_field='staffcode'),
        ),
    ]
