# Generated by Django 5.2.5 on 2025-08-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_accounting',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_auditor',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_data_entry',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_master',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_recovery_agent',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_reports',
        ),
    ]
