# Generated by Django 5.2.5 on 2025-08-19 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_fieldschedule_staff_alter_userprofile_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mortgage',
            options={'ordering': ['-mortgage_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='prepaid',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='prepaid',
            name='head',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='prepaid',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fieldschedule',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='StaffCode', limit_choices_to=models.Q(('status__iexact', 'active'), ('status', '1'), ('status', 1), ('status', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.staff', to_field='staffcode'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='deed_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='member_code',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='mortgage_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='member_code',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='StaffCode', limit_choices_to=models.Q(('status__iexact', 'active'), ('status', '1'), ('status', 1), ('status', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='companies.staff', to_field='staffcode'),
        ),
        migrations.AddIndex(
            model_name='mortgage',
            index=models.Index(fields=['member_code'], name='companies_m_member__e3e8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='mortgage',
            index=models.Index(fields=['deed_no'], name='companies_m_deed_no_d7c36c_idx'),
        ),
        migrations.AddIndex(
            model_name='mortgage',
            index=models.Index(fields=['mortgage_date'], name='companies_m_mortgag_c3b213_idx'),
        ),
        migrations.AddIndex(
            model_name='prepaid',
            index=models.Index(fields=['member_code'], name='companies_p_member__d11e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='prepaid',
            index=models.Index(fields=['date'], name='companies_p_date_fbdfed_idx'),
        ),
    ]
