# Generated by Django 5.2.5 on 2025-08-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_users_is_accounting_remove_users_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_reports',
            field=models.BooleanField(default=True),
        ),
    ]
