# Generated by Django 5.2.5 on 2025-08-19 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_mortgage_options_alter_prepaid_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', related_query_name='staff_member', to='companies.branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', related_query_name='user_profile', to='companies.branch'),
        ),
    ]
