# Generated by Django 5.2.5 on 2025-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_users_is_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_accounting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Admin: Comprehensive control over Enterprise workspace'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_auditor',
            field=models.BooleanField(default=False, help_text='Auditor: Read-only access to critical data and logs'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_data_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_loan_officer',
            field=models.BooleanField(default=False, help_text='Loan Officer: Tailored permissions for financial assessments'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_recovery_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_reports',
            field=models.BooleanField(default=False),
        ),
    ]
