# Generated by Django 5.2.5 on 2025-08-24 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_staff_branch_alter_userprofile_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldschedule',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='StaffCode', limit_choices_to={'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.staff', to_field='staffcode'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', related_query_name='staff_member', to='companies.branch'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('blocked', 'Blocked')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', related_query_name='user_profile', to='companies.branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='StaffCode', limit_choices_to={'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='companies.staff', to_field='staffcode'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
