# Generated by Django 5.2.5 on 2025-08-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_users_is_accounting_users_is_admin_users_is_auditor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='is_loan_officer',
            field=models.BooleanField(default=False, help_text='Loan Officer: Tailored permissions for financial assessments'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Admin: Comprehensive control over Enterprise workspace'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='is_auditor',
            field=models.BooleanField(default=False, help_text='Auditor: Read-only access to critical data and logs'),
        ),
    ]
