# Generated by Django 5.2.5 on 2025-08-25 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_backfill_staffcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldschedule',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='StaffCode', limit_choices_to=models.Q(('status', 'active'), models.Q(('staffcode__isnull', True), _negated=True), models.Q(('staffcode', ''), _negated=True)), null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.staff', to_field='staffcode'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffcode',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Empcode'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='StaffCode', limit_choices_to=models.Q(('status', 'active'), models.Q(('staffcode__isnull', True), _negated=True), models.Q(('staffcode', ''), _negated=True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='companies.staff', to_field='staffcode'),
        ),
    ]
