# Generated by Django 5.2.5 on 2025-08-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_userpermission_is_loan_officer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='is_auditor',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='is_loan_officer',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_auditor',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_loan_officer',
        ),
        migrations.AlterField(
            model_name='users',
            name='is_reports',
            field=models.BooleanField(default=True),
        ),
    ]
