# Generated by Django 5.2.5 on 2025-08-28 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_fieldschedule_staff_alter_staff_staffcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='companies.branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('status', 'active')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='companies.staff'),
        ),
    ]
