# Generated by Django 5.2.5 on 2025-08-31 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_fix_users_user_foreignkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_accounting',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_auditor',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_data_entry',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_master',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_recovery_agent',
        ),
        migrations.AlterField(
            model_name='users',
            name='is_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
