# Generated by Django 5.2.5 on 2025-09-01 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_staff_branch_alter_staff_contact1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='is_reports',
        ),
        migrations.AlterField(
            model_name='users',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='companies.staff'),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(condition=models.Q(('staff__isnull', False)), fields=('staff',), name='unique_user_per_staff'),
        ),
    ]
