# Generated by Django 5.2.5 on 2025-09-03 13:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_smlconfiguration_smlloantypeconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserCreation',
        ),
        migrations.AddField(
            model_name='branch',
            name='export_flag',
            field=models.BooleanField(default=False, help_text='Export flag for the branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address1',
            field=models.CharField(blank=True, help_text='Branch address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, help_text='Branch code (e.g., BRN001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(help_text='Company this branch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, help_text='Branch district', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(help_text='Branch name', max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, help_text='Branch phone number (10 digits)', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='smtcode',
            field=models.CharField(blank=True, db_column='SMTCode', db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='branch',
            table='companies_branch',
        ),
        migrations.AlterModelTable(
            name='client',
            table='companies_client',
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies_company',
        ),
        migrations.AlterModelTable(
            name='loanapplication',
            table='companies_loanapplication',
        ),
    ]
