# Generated by Django 5.2.5 on 2025-09-03 14:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_rename_users_usercreation_branch_export_flag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Users',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
        #         ('raw_csv_data', models.JSONField(blank=True, null=True)),
        #         ('full_name', models.CharField(blank=True, max_length=255, null=True)),
        #         ('department', models.CharField(blank=True, max_length=100, null=True)),
        #         ('mobile', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')])),
        #         ('is_reports', models.BooleanField(default=True)),
        #         ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('blocked', 'Blocked')], default='active', max_length=20)),
        #         ('password', models.CharField(blank=True, help_text='Hashed password for non-Django auth use', max_length=128, null=True)),
        #     ],
        # ),
        migrations.AlterModelOptions(
            name='usercreation',
            options={'verbose_name': 'User Creation', 'verbose_name_plural': 'User Creations'},
        ),
        # migrations.RemoveConstraint(
        #     model_name='usercreation',
        #     name='unique_user_per_staff',
        # ),
        migrations.RemoveField(
            model_name='branch',
            name='export_flag',
        ),
        migrations.AddField(
            model_name='usercreation',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='smtcode',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creations', to='companies.branch'),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='department',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='full_name',
            field=models.CharField(default='Unnamed User', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creations', to='companies.staff'),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_creation_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='branch',
            table=None,
        ),
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
        migrations.AlterModelTable(
            name='loanapplication',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usercreation',
            table='companies_user_creation',
        ),
        # migrations.AddField(
        #     model_name='users',
        #     name='branch',
        #     field=models.ForeignKey(blank=True, db_column='branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='companies.branch'),
        # ),
        # migrations.AddField(
        #     model_name='users',
        #     name='staff',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='companies.staff'),
        # ),
        # migrations.AddField(
        #     name='users',
        #     name='user',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='userpermission',
        #     name='user_profile',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_set', to='companies.users'),
        # ),
    ]
